GET http://34.125.39.227:4000/getCPU
Content-Type: application/json

###
GET http://34.125.39.227:4000/getRAM
Content-Type: application/json



###
POST http://34.125.39.227:4000/readCPU
Content-Type: application/json

{
    "id": 65,
    "name": "test44"
}

###
GET http://34.125.39.227:4000/readModCPU
Content-Type: application/json

###
GET http://34.125.39.227:4000/testRAM
Content-Type: application/json

###
GET http://34.125.39.227:4000/testCPU
Content-Type: application/json

###
GET http://34.125.39.227:4000/testProcess
Content-Type: application/json
